apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-react-app
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
        - name: my-react-app
          image: ryanboris/reactapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      restartPolicy: Always